repos:
  - repo: local
    hooks:
      - id: shell-lint
        name: Shell Syntax Check
        entry: pre_commit_hooks/shell-lint.sh
        language: script
        types: [shell]
        exclude: ^test/test\.sh$
